Adding my message to Say Something!
SavvasStephanides/say-something pull request #19
Opened 2023-10-13 14:05 UTC by sidxh

2023-10-13 15:19 UTC, sidxh commented
hey @SavvasStephanides can you merge this?

2023-10-13 15:42 UTC, SavvasStephanides requested changes
Please update the `language-quote` file 🙂

2023-10-14 17:31 UTC, SavvasStephanides approved these changes

2023-10-14 17:31 UTC, merged

2023-10-14 17:33 UTC, SavvasStephanides commented
Thanks for your submissions, Siddhant!

Here are your messages:

https://just-say-something.vercel.app/message/language-quote

https://just-say-something.vercel.app/message/addie-larue